# Generated by Django 3.2.6 on 2021-11-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('last_command', models.CharField(max_length=40)),
                ('last_movie', models.CharField(max_length=100)),
            ],
        ),
    ]
